### ISSUE TITLE
Feature: User can create an account

### ISSUE THREAD

**Issue by Susana-Gutierrez** [Susana-Gutierrez/loteria#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an account to play loteria

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User should be able to access to the loteria web page. 
User should see the 'Sign In' button on the home page. 
After clicking 'Sign In' button user should see two sections: Sign In and New Player?
User should be able to click on the 'Create Account' button and see the New Account form.
User should be able to fill the form adding First Name, Last Name, E-mail, Username, Password and click on 'Create User' to create a new account. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![feature 1-1](https://user-images.githubusercontent.com/82625148/158511639-dc9d3d26-0c4a-4aea-a4ba-f6b6298f0e28.jpg)
![feature 1-2](https://user-images.githubusercontent.com/82625148/158511649-2464fd51-986a-497d-924d-a80b239a39d7.jpg)
![feature 1 - 3](https://user-images.githubusercontent.com/82625148/158511654-68d23f01-fc03-434a-964f-1026e8f186ea.jpg)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Create data base
- [x] Update `schema.sql` 
- [x] Update `data.sql`

### ☁️ Server

- [x] Update `server/index.js` to ...
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create routing
- [x] Create home page
- [x] Create Sign In component
- [x] Create Sign In form
- [x] Build Create Account component
- [x] Create New account form

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by Susana-Gutierrez** [comment]
Completed
