### ISSUE TITLE
Feature: User can sign in

### ISSUE THREAD

**Issue by Susana-Gutierrez** [Susana-Gutierrez/loteria#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can Sign In to the web application.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can Sign In to the web application adding Username, and Password.
If the credentials are valid, user should be able to see the game main options.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![feature 2 -1](https://user-images.githubusercontent.com/82625148/158513128-82c38612-372b-4273-aa64-11d69caa6173.jpg)
![feature 2 - 2](https://user-images.githubusercontent.com/82625148/158513139-0e42017d-0ad1-4bfb-9511-aa2472228d58.jpg)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Execute a query against PostgreSQL database to verify if the user with the same username and password exists.

### ☁️ Server

- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a Sign In form component to get username and password information.
- [x] User should see an invalid credentials message if the username and password don't exist in the database.
- [x] User should see the game main options if the credentials are valid. 

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by Susana-Gutierrez** [comment]
Completed
