### ISSUE TITLE
Feature: User can review the profile

### ISSUE THREAD

**Issue by Susana-Gutierrez** [Susana-Gutierrez/loteria#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can review profile information

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to review personal information after signing in the web application.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![feature 3 - 1](https://user-images.githubusercontent.com/82625148/160256383-e7c6287e-64af-45a6-8ca3-6ed3ff06e3b5.jpg)

![feature 3 - 2](https://user-images.githubusercontent.com/82625148/160256392-7d242987-51f6-4a97-b180-b4f5e26bb21f.jpg)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Execute a query against PostgreSQL database to get user information that matches userId.

### ☁️ Server

- [x] Update `server/index.js` to ...
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create profile form page.
- [x] Update background component.
- [x] Update main menu page.

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by Susana-Gutierrez** [comment]
Completed
