### ISSUE TITLE
Feature: User can edit profile

### ISSUE THREAD

**Issue by Susana-Gutierrez** [Susana-Gutierrez/loteria#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit profile

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User should be able to change username, first name, last name and email information. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![feature-4](https://user-images.githubusercontent.com/82625148/161181924-69e5b105-2ddb-45d0-8799-b98ed46c2a0c.jpg)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Execute a query against PostgreSQL database to get user information that matches userId and update information

### ☁️ Server

- [x] Update `server/index.js` to ...
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create modal component 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by Susana-Gutierrez** [comment]
Completed
