### ISSUE TITLE
Feature: User can review game instructions

### ISSUE THREAD

**Issue by Susana-Gutierrez** [Susana-Gutierrez/loteria#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User can review game instructions 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will have access to a main menu section.
User will be able to click on 'Instructions' button to see the game instructions

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![feature-6](https://user-images.githubusercontent.com/82625148/161185414-38ee0a95-12ad-4939-b7a1-defca521cded.jpg)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a component to access to instructions section.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by Susana-Gutierrez** [comment]
Completed
