### ISSUE TITLE
Feature: User can create a game

### ISSUE THREAD

**Issue by Susana-Gutierrez** [Susana-Gutierrez/loteria#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a game

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Web app will generate a random game code after user clicks on the 'Create Game' button.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![feature-7](https://user-images.githubusercontent.com/82625148/161186461-9ba1c5e7-70c6-41a0-9c32-9ce56356ff32.jpg)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Game name will be save in the game table.

### ☁️ Server

- [x] Update `server/index.js` to ...
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to generate a random game code.
- [x] Update modal component to display the new game information

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by Susana-Gutierrez** [comment]
Completed
